# minimal CI script for the minimal runner
stages:
  - deploy

staging:
  stage: deploy
  script:
    - cd /var/www/nginx/$CI_PROJECT_NAME
    - git pull
    - npm ci
    - npm run build
  only:
    - master
